README.md
This PR adds a new `Packages` category, along with the `Depictr` and `Kakunin` Laravel packages.
=> feat: add new packages category

README.md
**Name**: PingCRM
**Description**: Inertia.js demonstration applications
=> add(other): PingCRM

README.md
**Name**: Titanium
**Link**: https://github.com/usetitanium/inertia
**Description**: Laravel front-end preset with Tailwind CSS, Inertia.js and Vue.js.
=> add(presets): Titanium

README.md
**Name**: _resource name here_
**Link**: _resource link here_
**Description**: _resource description here_
=> add: django adapter and demonstration application

README.md
**Name**: Ping CRM / Rails
**Link**: https://github.com/ledermann/pingcrm
**Description**: Ruby on Rails demo application to illustrate how Inertia.js works
=> add(other): Ping CRM / Rails

README.md
Closes https://github.com/innocenzi/awesome-inertiajs/issues/6
=> add(adapters): Fiber

README.md
| Node |https://github.com/jordankaerim/inertia-node |
This PR adds the Node middleware-based adapter.
---
=> add(adapters): Node

README.md
| CakePHP PingCRM | https://github.com/ishanvyas22/cakephp-pingcrm |
A demo application to illustrate how Inertia.js works with CakePHP.
---
=> add(other): Ping CRM / CakePHP

README.md
| _Masonite adapter_ | _https://github.com/girardinsamuel/masonite-inertia_ |
| _Ping CRM Masonite_ | _https://github.com/girardinsamuel/pingcrm-masonite_ |
---
- [+] My item is in the right category
- [+] My item has been added to the bottom of the list
- [+] My item's name and description respects the conventions of the list
- [+] I have read and followed the [contributing guidelines](.github/CONTRIBUTING.md)
=> add: Masonite adapter & Ping CRM

README.md
| Ping CRM / React | https://github.com/Landish/pingcrm-react |
Demonstration application made with React.
---
=> add(other): Ping CRM / React

README.md
| Inertia.js Tables for Laravel Query Builder | https://github.com/protonemedia/inertiajs-tables-laravel-query-builder |
Laravel package that provides DataTables-like features like searching, filtering, sorting, toggling columns, and pagination.
---
=> add(packages): Tables for Laravel

README.md
| Flask-inertia | https://github.com/j0ack/flask-inertia |
Flask adapter
---
=> add(adapters): Flask

README.md
| AdonisJS adapter | https://github.com/eidellev/inertiajs-adonisjs |
---
Thank you for your awesome work!
=> add(adapters): Adonis

README.md
| _Resource name here_ | _Resource link here_ |
---
=> add(other): Ping CRM / Flask

README.md
| Echo adapter | https://github.com/kohkimakimoto/inertia-echo |
| Ping CRM Echo | https://github.com/kohkimakimoto/pingcrm-echo |
---
=> add(adapters,resources): Echo adapter & Ping CRM

README.md
| _Mithril_ | _https://github.com/maicol07/inertia-mithril_ |
_The updated Mithril adapter for Inertia_
- Updated the link with the new package, updated for latest Inertia
- Labeled the old Mithril adapter as "up to Inertia 0.1)
---
=> update(mithril): Mithril adapter

README.md
| Grails Adapter | https://github.com/matrei/grails-inertia-plugin |
| PingCRM Grails/Vue.js | https://github.com/matrei/pingcrm-grails |
---
=> add(adapters,other): Grails Adapter & PingCRM

README.md
| ASP.NET Core | https://github.com/kapi2289/InertiaCore |
---
=> update(ASP.NET Core): change link to actively maintained project

README.md
| Laravel Jetstream React | https://github.com/ozziexsh/laravel-jetstream-react |
Converts the official Laravel Jetstream Inertia.js starter kit to React.
---
=> add(resources): Jetstream React

README.md
| _FastAPI_ | _https://github.com/hxjo/fastapi-inertia_ |
---
=> add(adapters): FastAPI adapter

README.md
Added [Hyperf](https://github.com/hyperf/hyperf) adapter for Inertia
=> add(adapters): hyperf

README.md
| _Resource name here_ | _Resource link here_ |
---
=> update(adapters): correct node adapter link
